name: Pipeline CI/CD con Docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Descarga el código del repositorio en la máquina virtual de GitHub
      - name: Descargar el repositorio
        uses: actions/checkout@v4

      # Step 2: Construye la imagen de Docker (Ejecuta las pruebas unitarias dentro del Dockerfile)
      - name: Construir imagen de Docker y ejecutar pruebas
        run: |
          cd app-contenedor
          docker build -t operaciones:v1 .

      # Step 3: Probar la ejecución del contenedor
      - name: Probar ejecución del contenedor
        run: |
          docker run --rm operaciones:v1